	try
		{
		}
	catch	(Exception exp)
		{
		Console.Error.WriteLine
		("*** error *** " + exp);
		Environment.Exit (1);
		}
